services:
  - type: web
    name: voice-note-summarizer
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
